// Leetcode 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added
let s = "abcd",
  t = "abcde";

let res = 0;
for (let i = 0; i < s.length; i++) {
  // sum_s+= s.charCodeAt(i);
  res = res ^ s.charCodeAt(i);
}
for (let i = 0; i < t.length; i++) {
  // sum_t+= t.charCodeAt(i);
  res = res ^ t.charCodeAt(i);
}

//let d = sum_t -sum_s;
console.log(String.fromCharCode(res));
